### ISSUE TITLE
Create `smallest_gap` & `within_gap` types

### ISSUE THREAD

**Issue by robinsones** [datacamp/funneljoin#3]
start with local (so can use `difftime`)

**Comment by dgrtwo** [comment]
I recommend taking interval argument as either a) a numeric representing the number of seconds or b) a difftime object.

Then you can write a utility function `as_seconds()`.

```
as_seconds <- function(x, sql = FALSE) {
  # If given as a number, units = "secs" is ignored
  ret <- as.double(x, units = "secs")
  
  if (sql) {
    ret <- dplyr::sql(sprintf("interval '%d seconds'", ret))
  }
  ret
}

as_seconds(20)

library(lubridate)  # has as.difftime

as_seconds(as.difftime(20, units = "hours"))
as_seconds(as.difftime(20, units = "days"))

as_seconds(as.difftime(20, units = "days"), sql = TRUE)
```

Note that you have to use !! if you use this in SQL dplyr. Check this out:

```
tbl_main_courses() %>%
  select(created_at, updated_at) %>%
  mutate(time_diff = updated_at - created_at) %>%
  filter(time_diff < !!as_seconds(as.difftime(10, unit = "days"), sql = TRUE)) %>%
  count()
```

In this approach, you do need to specify whether or not it's a remote table and set `sql =` accordingly. But try experimenting and the rest should work out.

**Comment by robinsones** [comment]
@dgrtwo, Anthony pointed out that time_diff in SQL is a character column. Another way we can do it is to make it an integer column with the number of seconds, which also takes away the need for `sql = TRUE` part of `as_seconds`. 

The SQL code to do this is: 

```
SELECT created_at, 
   updated_at,
   DATEDIFF('seconds', created_at, updated_at)::integer as time_diff
FROM main_app.courses
WHERE updated_at - created_at < 100000000
```

So two questions: 
1) What do you think of this approach instead?
2) Any thoughts on how to do this in dplyr 😅 ?

**Comment by robinsones** [comment]
Done! And with tests 🎉
